# Generated by Django 2.2.1 on 2019-05-08 12:24

from django.db import migrations, models
import django.db.models.deletion
import home.validators
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Background image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_key_words',
            field=models.TextField(blank=True, max_length=255, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(null=True, validators=[home.validators.ProhibitBlankRichTextValidator()], verbose_name='Short description'),
        ),
    ]
