# Generated by Django 2.2.1 on 2019-05-09 11:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='CityRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_model', to='events.City', verbose_name='City')),
                ('events', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_relationship', to='events.EventsPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
